version: '3'

services:
  mysqlsrv:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "12345"
      MYSQL_DATABASE: "desafio-dev"
    ports:
      - 3306:3306
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    ports:
      - 8085:8080
    networks:
      - mysql-compose-network

networks:
  mysql-compose-network:
    driver: bridge